In [93]:
import pandas as pd
import yfinance as yf

In [94]:
data=yf.download("NVDA",start="2004-01-01",end="2025-10-01")

/tmp/ipython-input-1773207528.py:1: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data=yf.download("NVDA",start="2004-01-01",end="2025-10-01")
[*********************100%***********************]  1 of 1 completed

In [95]:
data.head()

Price          Close      High       Low      Open      Volume
Ticker          NVDA      NVDA      NVDA      NVDA        NVDA
Date
2004-01-02  0.176347  0.182536  0.176347  0.180092   436416000
2004-01-05  0.182078  0.183301  0.177417  0.179022   575292000
2004-01-06  0.189490  0.192011  0.180703  0.181543  1093344000
2004-01-07  0.191171  0.192088  0.186052  0.187350   673032000
2004-01-08  0.191858  0.194456  0.190025  0.193539   433752000

In [96]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5471 entries, 2004-01-02 to 2025-09-30
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, NVDA)   5471 non-null   float64
 1   (High, NVDA)    5471 non-null   float64
 2   (Low, NVDA)     5471 non-null   float64
 3   (Open, NVDA)    5471 non-null   float64
 4   (Volume, NVDA)  5471 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 256.5 KB

In [97]:
data['Volume']=data['Volume'].astype(float)

In [98]:
data.shape

(5471, 5)

In [99]:
data.isnull().sum()

Price   Ticker
Close   NVDA      0
High    NVDA      0
Low     NVDA      0
Open    NVDA      0
Volume  NVDA      0
dtype: int64

In [ ]:
data['pct_change'] = (data['Close'] - data['Close'].shift(1))/ data['Close'].shift(1)
data['log_change'] = np.log(data['Close']/ data['Close'].shift(1))

In [100]:
import sys
sys.path.append('/content')

from technical_generator import Generator
Generator = Generator()

In [101]:
data['7ma'] = Generator.EMA(data['Close'], 7)
data['14ma'] = Generator.EMA(data['Close'], 14)
data['21ma'] = Generator.EMA(data['Close'], 21)
data['7macd'] = Generator.MACD(data['Close'], 3, 11, 7)
data['14macd'] = Generator.MACD(data['Close'], 7, 21, 14)
data['7rsi'] = Generator.RSI(data['Close'], 7)
data['14rsi'] = Generator.RSI(data['Close'], 14)
data['21rsi'] = Generator.RSI(data['Close'], 21)
data['7atr'] = Generator.atr(data['High'], data['Low'], 7)
data['14atr'] = Generator.atr(data['High'], data['Low'], 14)
data['21atr'] = Generator.atr(data['High'], data['Low'], 21)
data['7upper'], data['7lower'] = Generator.bollinger_band(data['Close'], 7)
data['14upper'], data['14lower'] = Generator.bollinger_band(data['Close'], 14)
data['21upper'], data['21lower'] = Generator.bollinger_band(data['Close'], 21)
data['7rsv'] = Generator.rsv(data['Close'], 7)
data['14rsv'] = Generator.rsv(data['Close'], 14)
data['21rsv'] = Generator.rsv(data['Close'], 21)

In [102]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5471 entries, 2004-01-02 to 2025-09-30
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   (Close, NVDA)   5471 non-null   float64
 1   (High, NVDA)    5471 non-null   float64
 2   (Low, NVDA)     5471 non-null   float64
 3   (Open, NVDA)    5471 non-null   float64
 4   (Volume, NVDA)  5471 non-null   float64
 5   (7ma, )         5471 non-null   float64
 6   (14ma, )        5471 non-null   float64
 7   (21ma, )        5471 non-null   float64
 8   (7macd, )       5471 non-null   float64
 9   (14macd, )      5471 non-null   float64
 10  (7rsi, )        5464 non-null   float64
 11  (14rsi, )       5457 non-null   float64
 12  (21rsi, )       5450 non-null   float64
 13  (7atr, )        5465 non-null   float64
 14  (14atr, )       5458 non-null   float64
 15  (21atr, )       5451 non-null   float64
 16  (7upper, )      5465 non-null   float64
 17  (7lower, )      5465 non-null   float64
 18  (14upper, )     5458 non-null   float64
 19  (14lower, )     5458 non-null   float64
 20  (21upper, )     5451 non-null   float64
 21  (21lower, )     5451 non-null   float64
 22  (7rsv, )        5465 non-null   float64
 23  (14rsv, )       5458 non-null   float64
 24  (21rsv, )       5451 non-null   float64
dtypes: float64(25)
memory usage: 1.1 MB

In [103]:
# tickers = ["AAPL", "QCOM", "AVGO", "MSFT", "AMZN", "NVDA", "TSLA",
#            "^GSPC", "^IXIC", "^DJI", "^VIX"]
tickers = ["AMD","INTC","QCOM","MU","TSM","005930.KS","MRVL",
    "MSFT","AMZN","GOOGL","AAPL",
    "ASML","AMAT","LRCX","KLAC",
    "SOXX","SMH","QQQ","XLK",
    "^VIX","^TNX","^IRX","DX-Y.NYB","GC=F","CL=F","QCOM","^GSPC", "^IXIC", "^DJI"
]
related_data = yf.download(tickers,start="2004-01-01",end="2025-10-01")['Close']

/tmp/ipython-input-1610305920.py:9: FutureWarning: YF.download() has changed argument auto_adjust default to True
  related_data = yf.download(tickers,start="2004-01-01",end="2025-10-01")['Close']
[*********************100%***********************]  28 of 28 completed

In [104]:
related_data.head()

Ticker,005930.KS,AAPL,AMAT,AMD,AMZN,ASML,CL=F,DX-Y.NYB,GC=F,GOOGL,...,SMH,SOXX,TSM,XLK,^DJI,^GSPC,^IRX,^IXIC,^TNX,^VIX
Date,,,,,,,,,,,,,,,,,,,,,
2004-01-01,6381.971191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2004-01-02,6353.670410,0.319414,16.040304,14.86,2.5950,19.395079,NaN,86.919998,NaN,NaN,...,17.632465,17.289137,4.303751,15.431395,10409.849609,1108.479980,0.902,2006.680054,4.373,18.219999
2004-01-05,6473.949707,0.332773,17.070948,15.20,2.6635,19.593477,33.779999,86.070000,424.399994,NaN,...,18.271324,17.851723,4.396435,15.808146,10544.070312,1122.219971,0.902,2047.359985,4.387,17.490000
2004-01-06,6509.326172,0.331572,17.361265,15.61,2.6515,19.791872,33.700001,85.629997,422.799988,NaN,...,18.377798,18.043823,4.400465,15.951309,10538.660156,1123.670044,0.901,2057.370117,4.277,16.730000
2004-01-07,6580.078613,0.339077,17.303205,15.66,2.5950,19.858000,33.619999,86.199997,421.899994,NaN,...,18.595007,18.205734,4.356139,16.026659,10529.030273,1126.329956,0.886,2077.679932,4.246,15.500000

In [105]:
related_data.isna().sum()

Ticker
005930.KS    241
AAPL         171
AMAT         171
AMD          171
AMZN         171
ASML         171
CL=F         175
DX-Y.NYB     158
GC=F         179
GOOGL        329
INTC         171
KLAC         171
LRCX         171
MRVL         171
MSFT         171
MU           171
QCOM         171
QQQ          171
SMH          171
SOXX         171
TSM          171
XLK          171
^DJI         171
^GSPC        171
^IRX         176
^IXIC        171
^TNX         176
^VIX         171
dtype: int64

In [106]:
related_data.dropna(inplace=True)

In [107]:
related_data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5056 entries, 2004-08-19 to 2025-09-30
Data columns (total 28 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   005930.KS  5056 non-null   float64
 1   AAPL       5056 non-null   float64
 2   AMAT       5056 non-null   float64
 3   AMD        5056 non-null   float64
 4   AMZN       5056 non-null   float64
 5   ASML       5056 non-null   float64
 6   CL=F       5056 non-null   float64
 7   DX-Y.NYB   5056 non-null   float64
 8   GC=F       5056 non-null   float64
 9   GOOGL      5056 non-null   float64
 10  INTC       5056 non-null   float64
 11  KLAC       5056 non-null   float64
 12  LRCX       5056 non-null   float64
 13  MRVL       5056 non-null   float64
 14  MSFT       5056 non-null   float64
 15  MU         5056 non-null   float64
 16  QCOM       5056 non-null   float64
 17  QQQ        5056 non-null   float64
 18  SMH        5056 non-null   float64
 19  SOXX       5056 non-null   float64
 20  TSM        5056 non-null   float64
 21  XLK        5056 non-null   float64
 22  ^DJI       5056 non-null   float64
 23  ^GSPC      5056 non-null   float64
 24  ^IRX       5056 non-null   float64
 25  ^IXIC      5056 non-null   float64
 26  ^TNX       5056 non-null   float64
 27  ^VIX       5056 non-null   float64
dtypes: float64(28)
memory usage: 1.1 MB

In [108]:
related_data.shape,data.shape

((5056, 28), (5471, 25))

In [109]:
# Flatten the MultiIndex in 'data'
data.columns = data.columns.get_level_values(0)

# Now merge the dataframes
dataset = data.merge(related_data, left_index=True, right_index=True)
display(dataset.head())

,Close,High,Low,Open,Volume,7ma,14ma,21ma,7macd,14macd,...,SMH,SOXX,TSM,XLK,^DJI,^GSPC,^IRX,^IXIC,^TNX,^VIX
Date,,,,,,,,,,,,,,,,,,,,,
2004-08-19,0.089091,0.090466,0.087716,0.088862,7.244040e+08,0.085997,0.090707,0.096837,0.006344,0.013478,...,12.879367,12.922947,3.433685,13.992236,10040.820312,1091.229980,1.442,1819.890015,4.211,16.959999
2004-08-20,0.094363,0.095661,0.088326,0.088633,1.199040e+09,0.088089,0.091195,0.096612,0.004371,0.012817,...,12.900661,13.010767,3.470857,14.060058,10110.139648,1098.349976,1.454,1838.020020,4.231,16.000000
2004-08-23,0.096426,0.097419,0.095356,0.095891,8.000280e+08,0.090173,0.091892,0.096595,0.002490,0.011964,...,13.032693,13.142493,3.508028,14.127869,10073.049805,1095.680054,1.477,1838.699951,4.279,15.880000
2004-08-24,0.092835,0.098260,0.091001,0.097801,9.394200e+08,0.090839,0.092018,0.096253,0.001277,0.011091,...,12.726041,12.857079,3.456918,14.052525,10098.629883,1096.189941,1.517,1836.890015,4.283,15.330000
2004-08-25,0.096807,0.097495,0.093140,0.094898,7.213080e+08,0.092331,0.092656,0.096304,0.000167,0.010142,...,12.875108,12.991554,3.568431,14.210758,10181.740234,1104.959961,1.512,1860.719971,4.261,14.980000

In [110]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5056 entries, 2004-08-19 to 2025-09-30
Data columns (total 53 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Close      5056 non-null   float64
 1   High       5056 non-null   float64
 2   Low        5056 non-null   float64
 3   Open       5056 non-null   float64
 4   Volume     5056 non-null   float64
 5   7ma        5056 non-null   float64
 6   14ma       5056 non-null   float64
 7   21ma       5056 non-null   float64
 8   7macd      5056 non-null   float64
 9   14macd     5056 non-null   float64
 10  7rsi       5056 non-null   float64
 11  14rsi      5056 non-null   float64
 12  21rsi      5056 non-null   float64
 13  7atr       5056 non-null   float64
 14  14atr      5056 non-null   float64
 15  21atr      5056 non-null   float64
 16  7upper     5056 non-null   float64
 17  7lower     5056 non-null   float64
 18  14upper    5056 non-null   float64
 19  14lower    5056 non-null   float64
 20  21upper    5056 non-null   float64
 21  21lower    5056 non-null   float64
 22  7rsv       5056 non-null   float64
 23  14rsv      5056 non-null   float64
 24  21rsv      5056 non-null   float64
 25  005930.KS  5056 non-null   float64
 26  AAPL       5056 non-null   float64
 27  AMAT       5056 non-null   float64
 28  AMD        5056 non-null   float64
 29  AMZN       5056 non-null   float64
 30  ASML       5056 non-null   float64
 31  CL=F       5056 non-null   float64
 32  DX-Y.NYB   5056 non-null   float64
 33  GC=F       5056 non-null   float64
 34  GOOGL      5056 non-null   float64
 35  INTC       5056 non-null   float64
 36  KLAC       5056 non-null   float64
 37  LRCX       5056 non-null   float64
 38  MRVL       5056 non-null   float64
 39  MSFT       5056 non-null   float64
 40  MU         5056 non-null   float64
 41  QCOM       5056 non-null   float64
 42  QQQ        5056 non-null   float64
 43  SMH        5056 non-null   float64
 44  SOXX       5056 non-null   float64
 45  TSM        5056 non-null   float64
 46  XLK        5056 non-null   float64
 47  ^DJI       5056 non-null   float64
 48  ^GSPC      5056 non-null   float64
 49  ^IRX       5056 non-null   float64
 50  ^IXIC      5056 non-null   float64
 51  ^TNX       5056 non-null   float64
 52  ^VIX       5056 non-null   float64
dtypes: float64(53)
memory usage: 2.1 MB

In [111]:
dataset.isnull().sum()

Close        0
High         0
Low          0
Open         0
Volume       0
7ma          0
14ma         0
21ma         0
7macd        0
14macd       0
7rsi         0
14rsi        0
21rsi        0
7atr         0
14atr        0
21atr        0
7upper       0
7lower       0
14upper      0
14lower      0
21upper      0
21lower      0
7rsv         0
14rsv        0
21rsv        0
005930.KS    0
AAPL         0
AMAT         0
AMD          0
AMZN         0
ASML         0
CL=F         0
DX-Y.NYB     0
GC=F         0
GOOGL        0
INTC         0
KLAC         0
LRCX         0
MRVL         0
MSFT         0
MU           0
QCOM         0
QQQ          0
SMH          0
SOXX         0
TSM          0
XLK          0
^DJI         0
^GSPC        0
^IRX         0
^IXIC        0
^TNX         0
^VIX         0
dtype: int64

In [112]:
dataset.to_csv('./dataset.csv',index=True)